export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const SELLER_LIST_SUCCESS = 'SELLER_LIST_SUCCESS';
export const SELLER_LIST_FAIL = 'SELLER_LIST_FAIL';